name: Sync to Hugging Face Space
on:
  push:
    branches: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to Space
        uses: huggingface/hub-action@v3
        with:
          repo-token: ${{ secrets.HUGGINGFACETOKEN }}
          repo-id: Beks1401/CSDS553_case_study_1_2025
          repo-type: space
